# Generated by Django 5.0.4 on 2024-05-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
