# Generated by Django 5.0.4 on 2024-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(upload_to='image/feature_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(upload_to='image/thumbnail_img/'),
        ),
    ]
