# Generated by Django 5.0.4 on 2024-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_feature_img_alter_post_thumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='', upload_to='image/user_img/'),
            preserve_default=False,
        ),
    ]
